version: '3'

services:
  app:
    depends_on:
      - mongo
    build: .
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "8000:8000"
    environment:
      - PORT=$PORT
      - VERSION=$VERSION
      - LOG_LEVEL=$LOG_LEVEL
    stdin_open: true
    tty: true
    volumes:
      - .:/usr/app
    command: npm start

  mongo:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db

volumes:
  mongodb:
